baseURL = "https://restoringeden.de"
languageCode = "en-uk"
title = "Restoring Eden"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "restoringeden"
  description = "Family, Faith, Germany, Christian, Jesus"
  message = ""

[social]
  facebook = "http://facebook.com/restoringeden.de"
  twitter = "https://twitter.com/restoringedende"
  instagram = "https://www.instagram.com/restoringeden.de/"
